name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "*/5 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
